// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AttachmentCache struct {
	ID                 int64
	CacheKind          string
	AttachmentKey      string
	SourceUrl          string
	Filename           string
	ContentType        string
	SizeBytes          int64
	Provider           string
	Model              string
	InstructionVersion string
	Content            string
	CreatedAt          int64
	UpdatedAt          int64
}

type BotEvent struct {
	ID         int64
	Timestamp  int64
	EventType  string
	GuildID    sql.NullString
	ChannelID  sql.NullString
	MessageID  sql.NullString
	UserID     sql.NullString
	Details    sql.NullString
	DurationMs sql.NullInt64
	Error      sql.NullString
}

type ConversationSummary struct {
	ID             int64
	GuildID        string
	UserID         string
	SummaryText    string
	MessageCount   int64
	StartMessageID sql.NullString
	EndMessageID   sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
	Embedding      interface{}
}

type DiscordMessage struct {
	MessageID           string
	ChannelID           string
	GuildID             string
	AuthorID            string
	AuthorUsername      string
	Content             string
	ReferencedMessageID string
	MessageJson         string
	CreatedAt           int64
	EditedAt            sql.NullInt64
	DeletedAt           sql.NullInt64
}

type DiscordMessageCacheState struct {
	ChannelID        string
	GuildID          string
	HistoryExhausted bool
	UpdatedAt        int64
}

type GuildSetting struct {
	ID      int64
	GuildID string
	Name    string
	Value   string
}

type MessageBuffer struct {
	ID               int64
	GuildID          string
	ChannelID        string
	MessageID        string
	UserID           string
	AuthorNick       string
	Content          string
	HasImage         sql.NullBool
	ImageDescription sql.NullString
	Timestamp        int64
	Processed        sql.NullBool
}

type VoiceSetting struct {
	GuildID         string
	AutoJoin        sql.NullBool
	AutoJoinChannel sql.NullString
	VoiceEnabled    sql.NullBool
	CreatedAt       sql.NullInt64
	UpdatedAt       sql.NullInt64
}
