// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteGuildSetting = `-- name: DeleteGuildSetting :exec
DELETE FROM guild_settings WHERE guild_id = ? AND name = ?
`

type DeleteGuildSettingParams struct {
	GuildID string
	Name    string
}

func (q *Queries) DeleteGuildSetting(ctx context.Context, arg DeleteGuildSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteGuildSetting, arg.GuildID, arg.Name)
	return err
}

const deleteOldEvents = `-- name: DeleteOldEvents :exec
DELETE FROM bot_events
WHERE timestamp < datetime('now', '-' || ? || ' days')
`

func (q *Queries) DeleteOldEvents(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldEvents, dollar_1)
	return err
}

const getAllGuilds = `-- name: GetAllGuilds :many
SELECT DISTINCT guild_id FROM guild_settings
`

func (q *Queries) GetAllGuilds(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var guild_id string
		if err := rows.Scan(&guild_id); err != nil {
			return nil, err
		}
		items = append(items, guild_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
SELECT timestamp, event_type, guild_id, channel_id, message_id, user_id, details, duration_ms, error
FROM bot_events
WHERE ? = 0 OR guild_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type GetEventsParams struct {
	Column1 interface{}
	GuildID sql.NullString
	Limit   int64
}

type GetEventsRow struct {
	Timestamp  int64
	EventType  string
	GuildID    sql.NullString
	ChannelID  sql.NullString
	MessageID  sql.NullString
	UserID     sql.NullString
	Details    sql.NullString
	DurationMs sql.NullInt64
	Error      sql.NullString
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, arg.Column1, arg.GuildID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.EventType,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.UserID,
			&i.Details,
			&i.DurationMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByMessage = `-- name: GetEventsByMessage :many
SELECT timestamp, event_type, guild_id, channel_id, message_id, user_id, details, duration_ms, error
FROM bot_events
WHERE message_id = ?
ORDER BY timestamp ASC
`

type GetEventsByMessageRow struct {
	Timestamp  int64
	EventType  string
	GuildID    sql.NullString
	ChannelID  sql.NullString
	MessageID  sql.NullString
	UserID     sql.NullString
	Details    sql.NullString
	DurationMs sql.NullInt64
	Error      sql.NullString
}

func (q *Queries) GetEventsByMessage(ctx context.Context, messageID sql.NullString) ([]GetEventsByMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByMessageRow
	for rows.Next() {
		var i GetEventsByMessageRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.EventType,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.UserID,
			&i.Details,
			&i.DurationMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT timestamp, event_type, guild_id, channel_id, message_id, user_id, details, duration_ms, error
FROM bot_events
WHERE event_type = ?
ORDER BY timestamp DESC
LIMIT ?
`

type GetEventsByTypeParams struct {
	EventType string
	Limit     int64
}

type GetEventsByTypeRow struct {
	Timestamp  int64
	EventType  string
	GuildID    sql.NullString
	ChannelID  sql.NullString
	MessageID  sql.NullString
	UserID     sql.NullString
	Details    sql.NullString
	DurationMs sql.NullInt64
	Error      sql.NullString
}

func (q *Queries) GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]GetEventsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByTypeRow
	for rows.Next() {
		var i GetEventsByTypeRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.EventType,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.UserID,
			&i.Details,
			&i.DurationMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildSetting = `-- name: GetGuildSetting :one
SELECT value FROM guild_settings WHERE guild_id = ? AND name = ?
`

type GetGuildSettingParams struct {
	GuildID string
	Name    string
}

func (q *Queries) GetGuildSetting(ctx context.Context, arg GetGuildSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getGuildSetting, arg.GuildID, arg.Name)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getGuildSettings = `-- name: GetGuildSettings :many
SELECT id, guild_id, name, value FROM guild_settings WHERE id = ?
`

func (q *Queries) GetGuildSettings(ctx context.Context, id int64) ([]GuildSetting, error) {
	rows, err := q.db.QueryContext(ctx, getGuildSettings, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildSetting
	for rows.Next() {
		var i GuildSetting
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO bot_events (timestamp, event_type, guild_id, channel_id, message_id, user_id, details, duration_ms, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Timestamp  int64
	EventType  string
	GuildID    sql.NullString
	ChannelID  sql.NullString
	MessageID  sql.NullString
	UserID     sql.NullString
	Details    sql.NullString
	DurationMs sql.NullInt64
	Error      sql.NullString
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.Timestamp,
		arg.EventType,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.UserID,
		arg.Details,
		arg.DurationMs,
		arg.Error,
	)
	return err
}

const setGuildSetting = `-- name: SetGuildSetting :exec
INSERT OR REPLACE INTO guild_settings (guild_id, name, value) VALUES (?, ?, ?)
`

type SetGuildSettingParams struct {
	GuildID string
	Name    string
	Value   string
}

func (q *Queries) SetGuildSetting(ctx context.Context, arg SetGuildSettingParams) error {
	_, err := q.db.ExecContext(ctx, setGuildSetting, arg.GuildID, arg.Name, arg.Value)
	return err
}
